Spring-boot basics - Introducing skeleton for spring data, example repository, temporary controller
RotateIT/RotateIT pull request #1
Opened 2017-07-11 19:27 UTC by wmilczarek

2017-07-11 22:11 UTC, ThePnx commented
+537 ? Please split it to 10 commits, max 54 lines per one.

2017-07-11 22:13 UTC, ThePnx commented
gradle-wrapper.jar should be excluded in git ignore.

2017-07-11 22:15 UTC, ThePnx commented
:+1: if you exclude gradle-wrapper.jar

2017-07-11 22:17 UTC, ThePnx requested changes
:+1:

2017-07-11 22:19 UTC, ThePnx reviewed
:+1:

2017-07-11 22:19 UTC, ThePnx commented on src/main/java/rotate/it/data/model/PullRequest.java
> +    public void setPullRequestId(String pullRequestId) {
Do we really need setters?

2017-07-11 22:56 UTC, ThePnx approved these changes

2017-07-12 05:14 UTC, wmilczarek commented
I have no idea what we will need in near future and you?

2017-07-12 05:15 UTC, merged