Upgrade gradle to 4.1
RotateIT/RotateIT pull request #50
Opened 2017-08-07 20:44 UTC by mateuszmarek

2017-08-07 20:49 UTC, ThePnx commented
I would like to take this opportunity to kindly remind you about #49

2017-08-07 22:20 UTC, ThePnx requested changes

2017-08-07 22:20 UTC, ThePnx commented on gradle/wrapper/gradle-wrapper.properties
>  zipStoreBase=GRADLE_USER_HOME
What about `distributionUrl` ?

2017-08-08 04:32 UTC, mateuszmarek commented on gradle/wrapper/gradle-wrapper.properties
>  zipStoreBase=GRADLE_USER_HOME
good catch!

2017-08-08 04:32 UTC, mateuszmarek commented on gradle/wrapper/gradle-wrapper.properties
>  zipStoreBase=GRADLE_USER_HOME
fixed

2017-08-08 06:00 UTC, ThePnx approved these changes

2017-08-08 06:00 UTC, merged